import type { Dataset } from "./types";

export const mockDataset: Dataset = {
  generatedAt: new Date().toISOString(),
  schemaVersion: 1,
  config: {
    maxSessions: null,
    users: 1,
    model: "mock",
    embeddingModel: null,
    apiBaseUrl: "mock",
  },
  users: [
    {
      id: "u1",
      displayName: "Demo User",
      team: "Strategy",
      avatarSeed: "u1",
      sessionCount: 1,
      totalTokens: 1000,
      totalCostUsd: 0.5,
      totalWasteUsd: 0.1,
      wizardScore: 0.7,
      outcomes: { fully: 1, mostly: 0, partial: 0, none: 0, unclear: 0 },
      topTools: { Read: 3, Edit: 2 },
      topFrictions: {},
      winRate: 1,
      costPerWin: 0.5,
      lastActiveAt: new Date().toISOString(),
      sessionsLast7d: 1,
      persona: "active",
      topFrictionLabel: "—",
    },
  ],
  sessions: [
    {
      sessionId: "s1",
      userId: "u1",
      filePath: "mock.jsonl",
      projectName: "demo",
      startedAt: new Date().toISOString(),
      endedAt: new Date().toISOString(),
      durationMinutes: 5,
      userMessageCount: 2,
      assistantMessageCount: 2,
      turns: 2,
      tokens: { input: 500, output: 500, cacheRead: 0, cacheCreate: 0 },
      models: { "claude-sonnet-4-6": 2 },
      tools: { Read: 3, Edit: 2 },
      toolErrors: 0,
      toolErrorCategories: {},
      userInterruptions: 0,
      branchPoints: 0,
      retryLoops: 0,
      abandoned: false,
      linesAdded: 10,
      linesRemoved: 2,
      filesModified: 1,
      costUsd: 0.5,
      wasteUsd: 0.1,
      wasteFlags: [],
      wizardScore: 0.7,
      goal: "Demo goal",
      outcome: "fully",
      sessionType: "single_task",
      friction: [],
      primarySuccess: "Shipped demo",
      briefSummary: "This is mock data — run `bun run analyze` to generate real data.",
      asks: [],
      unresolved: [],
      firstPrompt: "Hello",
    },
  ],
  clusters: [],
  aggregates: {
    totalSessions: 1,
    totalUsers: 1,
    totalTokens: 1000,
    totalCostUsd: 0.5,
    totalWasteUsd: 0.1,
    productiveUsd: 0.4,
    firmWinRate: 1,
    adoptionPct: 1,
    costPerLandedOutcome: 0.5,
    prevPeriodCostUsd: null,
    dateRange: {
      start: new Date(Date.now() - 7 * 86400000).toISOString(),
      end: new Date().toISOString(),
    },
    toolCounts: { Read: 3, Edit: 2 },
    modelMix: { "claude-sonnet-4-6": 2 },
    outcomeMix: { fully: 1 },
    frictionMix: {},
    wasteByType: {},
  },
};
